language: php
php:
  - 7.0

script:
  # Override default Travis script action [phpunit]
  - php -l *.php
  - composer install

# Enable Travis deployment
deploy:
  skip_cleanup: true
  # Use script as a deployment tool
  provider: script
  script: ./deploy/deploy.sh
  # Restrict deployment only for tags
  #on:
  #  tags: true

# Deployment script requires few enviromnet variables
env:
  global:
    - SVN_REPOSITORY=https://plugins.svn.wordpress.org/kkiapay-woocommerce
