name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  SVN_REPOSITORY: "https://plugins.svn.wordpress.org/kkiapay-woocommerce"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install
      
    - name: show variable
    - run: sh debug.sh 

    - name: run deploy shell script
      run: chmod +x ./deploy/debug.sh
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

